PROJECT_EXCEPTION_MESSAGE = "PROJECT Exception"
BUSINESS_EXCEPTION_MESSAGE = "Business Exception"
SYSTEM_EXCEPTION_MESSAGE = "System Exception"
DATA_EXCEPTION_MESSAGE = "Data Exception"

# Bisiness Exception
USER_AUTHENTICATION_FAIL_MESSAGE = "해당 ID의 사용자가 없습니다."
SESSION_NOT_FOUND_EXCEPTION_MESSAGE = "세션을 찾을 수 없습니다."
SESSION_EXPIRED_EXCEPTION_MESSAGE = "세션이 만료되었습니다."
SESSION_GUEST_BANNED_EXCEPTION_MESSAGE = "게스트 사용자는 접근할 수 없습니다."

# System Exception
REDIS_SYSTEM_EXCEPTION_MESSAGE = "Redis System Exception"
REDIS_INIT_DATA_EXCEPTION_MESSAGE = "데이터 초기화 중 오류 발생"

# Data Exception
DUPLICATE_DATA_EXCEPTION_MESSAGE = "중복된 데이터가 존재합니다."
