PROJECT_EXCEPTION_DETAIL = "PROJECT Exception"
SYSTEM_EXCEPTION_DETAIL = "System Exception"
DATABASE_EXCEPTION_DETAIL = "Database Exception"
BUSINESS_EXCEPTION_DETAIL = "Business Exception"

USER_AUTHENTICATION_FAIL_DETAIL = "해당 ID의 사용자가 없습니다."